### PR TITLE
Added a counter to track how many times the companies selection was changed.

### PR DESCRIPTION
**Pull request by ybaras**

### CODE REVIEW

**Comment by amitaibu** [comment]
Thanks.

**Comment by amitaibu** [comment]
@ybaras this doesn't seem to compile - were you able to make it work?

**Comment by ybaras** [comment]
Yes, I was. It works perfectly on my local machine. I will compare the files and try to find the error.

**Comment by ybaras** [comment]
@amitaibu You are correct. The app could not compile as I failed to properly commit the last file I modified (src/elm/Pages/Events/Router.elm).
I uploaded the file and then cloned to a new local folder just to make sure it works.

**Comment by amitaibu** [comment]
> I uploaded the file

Are you sure? I don't see it in the PR

**Comment by ybaras** [comment]
Well, the PR is closed. I will send a new one.

**Pull request closed without merging**
