### PR TITLE
Elm runtime error

### PR DESCRIPTION
**Pull request by amitaibu**
In this PR I'm able to get a runtime error whenever changing the select list

elm

Seems to be `EventAuthorFilter.View.view` triggering it. @rgrempel I wonder if you have ever came across something like that?

Next step is probably to try and reduce the error to the minimum code needed outside of hedley :/

### CODE REVIEW

**Comment by rgrempel** [comment]
I checked out the `getAsError` branch, and I couldn't get it to compile without error unless I made the following change:

```
diff --git a/src/elm/Event/Decoder.elm b/src/elm/Event/Decoder.elm
index 5507e00..05f062d 100644
--- a/src/elm/Event/Decoder.elm
+++ b/src/elm/Event/Decoder.elm
@@ -30,7 +30,7 @@ decode =
     JD.at ["data"]
       <| JD.list
       <| JD.object4 Event
+        ("user" := author)
         ("id" := number)
         ("label" := JD.string)
         ("location" := marker)
-        ("user" := author)
```

I wonder if you might have a problem with stale build artifacts -- what happens if you do a `rm -r elm-stuff/build-artifacts` to clean them out? It's possible that you'll see this error then when you compile, and it's possible that fixing this error fixes the problem.

I did try running the app after this change, but I'm not connecting to the server properly ... I can try to figure that out, if this doesn't fix things.

**Comment by amitaibu** [comment]
Thanks for looking at this. Probably indeed a stale build, because I'm seeing this compile error now. I'll try to fix the compile and see if the error persists.

> but I'm not connecting to the server properly

Oh, sorry, I switched it back to a non-local install had to do it as I was on flight :)

**Comment by amitaibu** [comment]
Seems it was indeed a stale build. Weird, haven't came accross such a case yet - I'll be sure to keep an eye now. Sorry for the noise, and thanks for the help @rgrempel :)

**Comment by rgrempel** [comment]
I've seen it happen from time to time -- there's something about the way in which elm-make calculates which files need to be re-compiled that isn't quite perfect. Either that, or sometimes switching branches may confuse the timestamps as between source files and built files. Anyway, if anything really strange happens, I always reach for `rm -r elm-stuff/build-artifacts` and see if re-compiling everything helps.

**Comment by amitaibu** [comment]
:+1:

**Pull request closed without merging**
